---
- name: Install Python packages
  apt:
    name: "{{ python_packages }}"
    state: latest
    update_cache: yes

- name: Clone Git repository
  git:
    repo: "https://github.com/chandradeoarya/todolist-flask.git"
    dest: "/home/ubuntu/todolist"
    clone: yes
    update: yes
    version: 'env'

- name: Create Python virtual environment
  command:
    cmd: python3 -m venv /home/ubuntu/todolist/venv
    creates: /home/ubuntu/todolist/venv

- name: Install requirements
  pip:
    requirements: /home/ubuntu/todolist/requirements.txt
    virtualenv: /home/ubuntu/todolist/venv
    virtualenv_command: python3 -m venv

- name: Create .env file in todo directory
  copy:
    dest: "/home/ubuntu/todolist-flask/.env"
    content: |
      MYSQL_DATABASE_HOST={{ mysql_db_host }}
      MYSQL_DATABASE_USER={{ mysql_db_user }}
      MYSQL_DATABASE_PASSWORD={{ mysql_db_password }}
      MYSQL_DATABASE_PORT=3306

    mode: '0644'

- name: Create systemd service file for the todolist
  template:
    src: todolist.service.j2
    dest: /etc/systemd/system/todolist.service
    mode: '0644'

- name: Reload systemd to read new todolist service
  systemd:
    daemon_reload: yes

- name: Enable and start todolist service
  systemd:
    name: todolist
    enabled: yes
    state: started
