---
- hosts: tag_Type_database
  become: yes
  vars:
    ansible_user: "ubuntu"
    ansible_ssh_private_key_file: "../stephan.pem"
  vars_files:
    - ../../secret_vars.yaml
  roles:
    - ../roles/ubuntu_setup
    - ../roles/database_setup
